import { Document, Page, View, Text } from "@react-pdf/renderer";
import { sharedStyles as s } from "@/lib/pdf/styles";
import { formatDisplayDate } from "@/lib/dates";
import type { ClinicSettingsRow } from "@/types/database";

export interface ReportPdfData {
  clinicSettings: ClinicSettingsRow | null;
  reportTitle: string;
  rangeLabel: string;
  generatedAtIso: string;
  generatedByName: string;
  metrics: Array<{ label: string; value: string }>;
  tableHeaders: string[];
  /** Column widths as percentages, summing to 100 — must match tableHeaders.length. */
  tableColumnWidths: number[];
  tableRows: string[][];
  /** True row count before any cap was applied — see pdfService's MAX_REPORT_PDF_ROWS. */
  totalRowCount: number;
}

/** Any of the four Reports-page report types (spec section 43), rendered generically from already-computed reportService output — same summary/table data the on-screen page and the CSV export use, just laid out for print. */
export function ReportDocument({
  clinicSettings,
  reportTitle,
  rangeLabel,
  generatedAtIso,
  generatedByName,
  metrics,
  tableHeaders,
  tableColumnWidths,
  tableRows,
  totalRowCount,
}: ReportPdfData) {
  return (
    <Document title={`Felis Clinic - ${reportTitle}`}>
      <Page size="A4" style={s.page} orientation={tableHeaders.length > 5 ? "landscape" : "portrait"}>
        <View style={s.header}>
          <View>
            <Text style={s.clinicName}>{clinicSettings?.clinic_name ?? "Felis Clinic"}</Text>
            <Text style={s.clinicMeta}>{clinicSettings?.address ?? "Marondera, Zimbabwe"}</Text>
          </View>
          <View>
            <Text style={s.docTitle}>{reportTitle}</Text>
            <Text style={s.docMeta}>{rangeLabel}</Text>
            <Text style={s.docMeta}>Generated {formatDisplayDate(generatedAtIso)}</Text>
          </View>
        </View>

        <View style={s.fieldGrid}>
          {metrics.map((metric) => (
            <View key={metric.label} style={[s.field, { width: "25%" }]}>
              <Text style={s.fieldLabel}>{metric.label}</Text>
              <Text style={s.fieldValue}>{metric.value}</Text>
            </View>
          ))}
        </View>

        <Text style={s.sectionTitle}>Detail</Text>
        {tableRows.length === 0 ? (
          <Text style={s.fieldValue}>No records in this range.</Text>
        ) : (
          <View style={s.table}>
            <View style={s.tableHeaderRow}>
              {tableHeaders.map((header, i) => (
                <Text key={header} style={[s.tableHeaderCell, { width: `${tableColumnWidths[i]}%` }]}>
                  {header}
                </Text>
              ))}
            </View>
            {tableRows.map((row, rowIndex) => (
              <View key={rowIndex} style={rowIndex === tableRows.length - 1 ? s.tableRowLast : s.tableRow}>
                {row.map((cell, cellIndex) => (
                  <Text key={cellIndex} style={[s.tableCell, { width: `${tableColumnWidths[cellIndex]}%` }]}>
                    {cell || "—"}
                  </Text>
                ))}
              </View>
            ))}
          </View>
        )}

        {totalRowCount > tableRows.length ? (
          <Text style={s.note}>
            Showing the first {tableRows.length} of {totalRowCount} records. Export CSV from the Reports
            page for the complete list.
          </Text>
        ) : null}

        <Text style={s.footer} fixed>
          Generated by {generatedByName} on {formatDisplayDate(generatedAtIso)} · Felis Clinic ANC Management
          System
        </Text>
      </Page>
    </Document>
  );
}
